@echo off
REM Push Hotfix 7 (Draw-mode Close + Enter commit) - generated by Cowork.
REM Vic runs this from cmd in the repo root.
REM
REM Step 1: clear any stale .git/*.lock files left by the Linux-mount
REM         side of the Cowork session (Windows can delete them; Linux
REM         cannot due to mount permission asymmetry).
REM Step 2: git push origin main.

cd /D "%~dp0"

echo === Clearing stale .git lock files ===
if exist ".git\index.lock" del /f /q ".git\index.lock"
if exist ".git\HEAD.lock" del /f /q ".git\HEAD.lock"
for /r ".git\objects" %%f in (tmp_obj_*) do del /f /q "%%f"

echo.
echo === git status ===
git status

echo.
echo === Commits to push ===
git log origin/main..HEAD --oneline

echo.
echo === Pushing to origin/main ===
git push origin main

echo.
echo Done. Vercel will auto-deploy.
pause
