import { useState } from 'react';
import { ConceptNote, Eyebrow, LiveDesigner, MeetingCard, PitchShell, StatusChip } from './PitchShell';
import { MERCHANT_CLIENTS, currentSearch, examplePartnerShare, readPitchClient, type MerchantClient } from './workflowModel';

const CHAPTERS = ['The opportunity', 'Your categories', 'Your storefront', 'Partner together', 'Grow with care'];
/** Each category describes what the designer does for it today; `boundary` is what it does not claim. */
const CATEGORIES = [
  { id: 'solar', icon: '☀', title: 'Solar', result: 'A roof becomes an energy conversation.', detail: 'Place panels on the roof level, set the hour of day, and read a plain-English energy meter beside the plan.', metric: 'Roof + sun → energy estimate', boundary: 'An estimate is not guaranteed output. Installation design and supplier validation are still required.' },
  { id: 'build', icon: '⌂', title: 'Build', result: 'Help clients understand the whole home.', detail: 'Draw walls, cut doors and windows, lay floors and a roof, then walk the result in Premium 3D before choosing construction materials.', metric: 'Dimensions → visible scope', boundary: 'Visual planning supports the conversation; professional drawings, structural design and approvals remain separate.' },
  { id: 'paint', icon: '◒', title: 'Paint', result: 'Turn a colour into a room decision.', detail: 'Pick from the TintEX and Sofap ranges; the wall shows that shade in the plan and in 3D, and coverage turns wall area into tins at the tin price.', metric: 'Wall area → tins', boundary: 'Lighting and screens affect appearance. Confirm colour samples, substrate, coverage and preparation with the supplier.' },
  { id: 'floor', icon: '▦', title: 'Flooring', result: 'Let the floor connect the whole scheme.', detail: 'Lay a floor across one room or the whole plan and watch the coverage count, then connect it to your packs.', metric: 'Room area → pack planning', boundary: 'Allow for cuts, waste, batch matching and the installer’s site measurements before ordering.' },
  { id: 'lighting', icon: '✳', title: 'Lighting', result: 'Sell atmosphere with a clear specification.', detail: 'Place lights alongside furniture and finishes; each item carries its watts into the plan’s simple electrics meter.', metric: 'Placement → connected load', boundary: 'The preview is not a certified lighting calculation or electrical installation design.' },
  { id: 'furniture', icon: '▱', title: 'Furniture', result: 'Give every product a sense of scale.', detail: 'Move, rotate and compare products at their data-sheet dimensions; the Courts range is in the demo today, in 2D and 3D.', metric: 'Supplier dimensions → spatial fit', boundary: '2D is to scale using supplied dimensions. A product wears its own 3D body or its own artwork, never a stand-in.' },
  { id: 'garden', icon: '♧', title: 'Garden', result: 'Continue the design beyond the door.', detail: 'Lay lawn, paths and paving, add outdoor products and a Duraco water tank alongside the home and its site.', metric: 'Outdoor space → material choices', boundary: 'Ground conditions, drainage, boundaries and installation quantities require site confirmation.' },
] as const;
type CategoryId = (typeof CATEGORIES)[number]['id'];
type Channel = 'embed' | 'studio' | 'shop';
const FINANCE_STEPS = [
  { title: 'Agree the quote', copy: 'The customer reviews a real supplier quote, scope and exclusions before entering any finance journey.' },
  { title: 'Give informed consent', copy: 'Explain the selected provider, information needed and the customer’s choices before any transfer.' },
  { title: 'Verify with a secure provider', copy: 'Identity documents belong in an approved identity or finance provider’s secure flow. This presentation does not collect IDs.' },
  { title: 'Review & sign', copy: 'The provider makes its own eligibility decision. E-signature, final terms and any payment mandate require a supported integration.' },
];
/** A client overlay changes words and defaults, never routes or structure. No prices anywhere. */
const CLIENTS: Record<MerchantClient, { name: string; eyebrow: string; headline: string; lead: string; artLabel: string; category: CategoryId; channel: Channel; inBuild: string[]; laterPhase: string }> = {
  'spa-concept': {
    name: 'Spa Concept',
    eyebrow: 'Spa Concept · internal tool first',
    headline: 'Design a hammam or sauna in 3D, and know the wood the moment you do.',
    lead: 'Your staff design in the studio and share a design when they choose to. Today the room, its walls, floors and finishes design in 2D and 3D; the wood and cladding count from that drawn room is in build.',
    artLabel: 'Your team designs. Your client sees what you share.',
    category: 'build',
    channel: 'studio',
    inBuild: ['Wood and cladding quantity from the drawn room', 'Staff dashboard for your designers', 'Permission locks: who may change what', 'Hold-for-review ordering before anything is released'],
    laterPhase: 'Customer access is a later, locked phase: nothing opens to the public until you switch it on.',
  },
};

export default function MerchantPitchPage() {
  const [client] = useState(() => readPitchClient(currentSearch(), MERCHANT_CLIENTS));
  const overlay = client ? CLIENTS[client] : null;
  const [chapter, setChapter] = useState(0);
  const [categoryId, setCategoryId] = useState<CategoryId>(overlay?.category ?? 'paint');
  const [channel, setChannel] = useState<Channel>(overlay?.channel ?? 'embed');
  const [view, setView] = useState<'2d' | '3d'>('3d');
  const [partner, setPartner] = useState('Paint + flooring');
  const [orderValue, setOrderValue] = useState(25000);
  const [rate, setRate] = useState(5);
  const [financeStep, setFinanceStep] = useState(0);
  const category = CATEGORIES.find((item) => item.id === categoryId)!;
  const share = examplePartnerShare(orderValue, rate);
  const categoryButtons = <div className="pitch-category-grid" role="group" aria-label="Product categories">{CATEGORIES.map((item) => <button type="button" key={item.id} aria-pressed={categoryId === item.id} onClick={() => setCategoryId(item.id)}><span aria-hidden="true">{item.icon}</span>{item.title}</button>)}</div>;
  const channels: { id: Channel; name: string; caption: string }[] = [
    { id: 'embed', name: 'On your website', caption: overlay ? 'Later, locked phase' : 'A design experience within your site' },
    { id: 'studio', name: 'Standalone studio', caption: overlay ? 'Your staff design here first' : 'A dedicated destination for projects' },
    { id: 'shop', name: 'Connected shop', caption: 'Products with space and context' },
  ];

  return <PitchShell audience="Merchants" chapters={CHAPTERS} chapter={chapter} onChapter={setChapter}>
    {chapter === 0 && <div className="pitch-hero"><div className="pitch-hero-copy"><Eyebrow>{overlay?.eyebrow ?? 'Products, in the places they belong'}</Eyebrow>{overlay ? <h1 className="pitch-h1-client">{overlay.headline}</h1> : <h1>From browsing<br />to <em>“that’s my home.”</em></h1>}<p className="pitch-lead">{overlay?.lead ?? 'Give customers a place to try your products at true scale, in a 2D plan and Premium 3D, with colour-true paint and honest quantities, and hand your team a confident brief.'}</p><div className="pitch-chip-row">{overlay ? <><StatusChip available>Room, walls, floors and finishes · live in 3D</StatusChip><StatusChip building>Wood and cladding quantity · in build</StatusChip><StatusChip>Customer access · later, locked phase</StatusChip></> : <><StatusChip available>Live design experience · 2D + 3D</StatusChip><StatusChip>Your brand & shop connection · integration required</StatusChip></>}</div><button type="button" className="pitch-primary" onClick={() => setChapter(1)}>Explore your possibilities <span aria-hidden="true">↗</span></button><div className="pitch-hero-metrics"><span><strong>See</strong>Products in context</span><span><strong>Plan</strong>Quantities & space</span><span><strong>Connect</strong>To your team</span></div></div><figure className="pitch-hero-art"><img src="/showcase/merchant-vision.webp" alt="Architectural concept showing an elegant home with furniture, materials, outdoor design and solar panels" /><figcaption>Architectural concept imagery · product appearance depends on supplied data</figcaption><div className="pitch-art-label"><span className="pitch-status-dot" /> {overlay?.artLabel ?? 'A shop window with room to explore.'}</div></figure></div>}

    {chapter === 1 && <div className="pitch-split"><aside className="pitch-panel pitch-panel-ivory"><Eyebrow>One platform, many conversations</Eyebrow><h2>What do you help<br />people create?</h2><p>Choose a category to explore the experience and the information that makes it useful.</p>{categoryButtons}<p className="pitch-fine">Keep actual brand, product, price and supplier attribution attached to the catalogue.</p></aside><div className={`pitch-panel pitch-panel-dark pitch-category-story ${overlay ? 'has-build-list' : ''}`}><span className="pitch-category-symbol" aria-hidden="true">{category.icon}</span><StatusChip available>{category.title} design context</StatusChip><h2>{category.result}</h2><p className="pitch-lead">{category.detail}</p><div className="pitch-flow-diagram"><span>Explore</span><i aria-hidden="true">→</i><span>Configure</span><i aria-hidden="true">→</i><span>Review</span></div><div className="pitch-category-metric">{category.metric}</div><p className="pitch-fine">{category.boundary}</p>{overlay && <div className="pitch-build-list" data-testid="in-build"><Eyebrow>In build for {overlay.name}</Eyebrow>{overlay.inBuild.map((line) => <div key={line}><StatusChip building>in build</StatusChip><span>{line}</span></div>)}<p className="pitch-fine">{overlay.laterPhase}</p></div>}<button type="button" className="pitch-primary" onClick={() => setChapter(2)}>Try a storefront configuration ↗</button></div></div>}

    {chapter === 2 && <div className="pitch-split pitch-storefront-stage"><aside className="pitch-panel pitch-panel-ivory"><Eyebrow>{overlay ? 'Your team first, your customers later' : 'Meet customers where they are'}</Eyebrow><h2>Your experience.<br />Three ways in.</h2><div className="pitch-channel-list" role="group" aria-label="Storefront channel">{channels.map((item) => <button type="button" key={item.id} aria-pressed={channel === item.id} onClick={() => setChannel(item.id)}><span>{channel === item.id ? '●' : '○'}</span><div><strong>{item.name}</strong><small>{item.caption}</small></div><span aria-hidden="true">↗</span></button>)}</div><label className="pitch-select-label">Starting conversation<select value={categoryId} onChange={(event) => setCategoryId(event.target.value as CategoryId)}>{CATEGORIES.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><div className="pitch-segment" aria-label="Designer view"><button type="button" aria-pressed={view === '2d'} onClick={() => setView('2d')}>2D · to scale</button><button type="button" aria-pressed={view === '3d'} onClick={() => setView('3d')}>Premium 3D</button></div><p className="pitch-fine">Supplier dimensions drive scale. In 3D a product wears its own body or its own artwork; the demo is read-only and places no orders.</p><ConceptNote>Channel and category choices preview the setup. Branding, embedding on your domain and connecting your shop require configuration; no website is changed here.</ConceptNote></aside><div className="pitch-panel pitch-panel-dark pitch-storefront-preview"><div className="pitch-preview-browser"><span /><span /><span /><strong>{channel === 'embed' ? 'Your website / design a space' : channel === 'studio' ? 'Your dedicated studio' : 'Your shop / see it at home'}</strong></div><div className="pitch-storefront-title"><div><Eyebrow>{category.title} collection</Eyebrow><h3>{channel === 'shop' ? 'See how it fits.' : 'Make room for your ideas.'}</h3></div><StatusChip available>Live designer</StatusChip></div><LiveDesigner scene={categoryId === 'paint' ? 'paint' : 'home'} view={view} onViewChange={setView} /><div className="pitch-preview-actions"><a href={channel === 'shop' ? '/products' : '/studio'}>{channel === 'shop' ? 'Browse the product shop' : 'Open standalone studio'} ↗</a><a href="/demo">Explore all demo options ↗</a></div></div></div>}

    {chapter === 3 && <div className="pitch-split"><div className="pitch-panel pitch-panel-dark"><Eyebrow>A useful network, on agreed terms</Eyebrow><h2>One home.<br />Complementary expertise.</h2><p className="pitch-lead">A paint choice can introduce flooring. A roof project can introduce solar. Let the customer keep the whole design in view.</p><div className="pitch-segment pitch-wrap" aria-label="Example partner combination">{['Paint + flooring', 'Build + solar', 'Furniture + lighting'].map((item) => <button type="button" key={item} aria-pressed={partner === item} onClick={() => setPartner(item)}>{item}</button>)}</div><div className="pitch-partner-map"><span>{partner.split(' + ')[0]}</span><div><span className="pitch-brand-mark">P<span>·</span></span><strong>Shared design context</strong><small>Customer choice and consent</small></div><span>{partner.split(' + ')[1]}</span></div><div className="pitch-token-row"><span>Clear supplier ownership</span><span>Customer consent</span><span>Agreed attribution</span></div><ConceptNote>Partner routing, referral tracking and settlements require agreements and integration. No referral or commission is created here.</ConceptNote></div><aside className="pitch-panel pitch-panel-ivory"><Eyebrow>Commercial conversation · example only</Eyebrow><h3>Make the agreement explicit.</h3><p>Try an illustrative share to discuss terms with a partner. This hypothetical partner share is separate from platform commission. It is neither an offer nor a guaranteed payment.</p><div className="pitch-form-grid"><label>Eligible order value · Rs<input aria-label="Example eligible order value" type="number" min="0" value={orderValue} onChange={(event) => setOrderValue(Math.max(0, Number(event.target.value)))} /></label><label>Agreed share example · %<input aria-label="Example partner share percentage" type="number" min="0" max="100" value={rate} onChange={(event) => setRate(Math.min(100, Math.max(0, Number(event.target.value))))} /></label></div><div className="pitch-share-result" aria-live="polite"><span>Illustrative partner share</span><strong>Rs {share?.toLocaleString('en-MU', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) ?? '—'}</strong><small>Order basis × agreed percentage</small></div><ul className="pitch-check-list"><li>Define eligible products and attribution period</li><li>Agree tax, delivery and discount treatment</li><li>Handle cancellations, returns and disputes</li><li>Set approval, reconciliation and payment terms</li></ul><p className="pitch-fine">Final agreements determine the calculation and any entitlement.</p></aside></div>}

    {chapter === 4 && <div className="pitch-growth-stage"><div className="pitch-growth-columns"><article className="pitch-panel pitch-panel-ivory"><Eyebrow>A catalogue that stays useful</Eyebrow><h2>Your team owns<br />the product detail.</h2><StatusChip available>Authenticated merchant tools</StatusChip>{overlay && <StatusChip building>Staff dashboard and permission locks · in build</StatusChip>}<p>Existing authorized merchant dashboards support catalogue maintenance. Accurate dimensions, prices, coverage and product images make the design experience more useful.</p><div className="pitch-token-row"><span>Supplier dimensions</span><span>Real prices</span><span>Product assets</span><span>Coverage & packs</span></div><p className="pitch-fine">Use your assigned merchant access. This public presentation does not grant catalogue editing permissions.</p><a className="pitch-secondary" href="/studio/merchants">Open merchant access ↗</a></article><article className="pitch-panel pitch-panel-dark"><Eyebrow>Optional future journey</Eyebrow><h3>Finance & signing,<br />with the right providers.</h3><div className="pitch-finance-steps" role="group" aria-label="Finance workflow preview">{FINANCE_STEPS.map((step, index) => <button key={step.title} type="button" aria-pressed={financeStep === index} onClick={() => setFinanceStep(index)}><span>{index + 1}</span>{step.title}</button>)}</div><div className="pitch-finance-copy" aria-live="polite"><strong>{FINANCE_STEPS[financeStep].title}</strong><p>{FINANCE_STEPS[financeStep].copy}</p></div><ConceptNote>Integration required for finance, secure identity, e-signature, payments and automated emails. No identity documents are collected and no application is submitted here.</ConceptNote></article></div><MeetingCard /></div>}
  </PitchShell>;
}
