import { useState } from 'react';
import { EmbeddedDesigner } from '../../demo/EmbeddedDesigner';
import { PitchEnquiryForm, type PitchAudience } from './PitchEnquiryForm';
import { MEETING_URL } from './workflowModel';

const STORIES = {
  developers: { heading: 'From a buyer’s brief to a measured starting point.', prompt: 'Draft a two-bedroom home with a living room, kitchen and bathroom.', outcome: 'Review room sizes and circulation with the buyer, then refine the shared plan and its product choices.', connection: 'Start with one apartment type, your approved product ranges and the decisions buyers are allowed to change.' },
  merchants: { heading: 'Let a customer design around your products.', prompt: 'Draft a living room and kitchen within an 8 by 6 metre footprint.', outcome: 'Review real catalogue dimensions and product choices in the customer’s room, then refine finishes and quantities.', connection: 'Map your catalogue fields and units, validate the data, then publish through your authenticated merchant account.' },
  construction: { heading: 'A clear brief. A measurable design. A reviewable quantity.', prompt: 'Draft a two-bedroom house, then review wall and roof materials.', outcome: 'Inspect geometry in 2D and 3D. Open Materials for editable block, mortar, concrete and roof estimates.', connection: 'Bring your block dimensions, pack sizes, material specifications and catalogue references into one reviewed brief.' },
} as const;

export function PitchConnectChapter({ audience, initialSection = 'ai' }: { audience: PitchAudience; initialSection?: 'ai' | 'connect' | 'contact' }) {
  const [section, setSection] = useState(initialSection);
  const [view, setView] = useState<'2d' | '3d'>('3d');
  const [live, setLive] = useState(false);
  const story = STORIES[audience];
  return <div className="pitch-connect-stage">
    <div className="pitch-connect-heading"><div><p className="pitch-eyebrow">AI + your business</p><h2>Less repetition.{' '}<br /><em>More considered decisions.</em></h2></div><div className="pitch-segment pitch-wrap" role="group" aria-label="AI and business chapter"><button type="button" aria-pressed={section === 'ai'} onClick={() => setSection('ai')}>1 · Try AI design</button><button type="button" aria-pressed={section === 'connect'} onClick={() => setSection('connect')}>2 · Connect your business</button><button type="button" aria-pressed={section === 'contact'} onClick={() => setSection('contact')}>3 · Feedback & meetings</button></div></div>
    {section === 'ai' && <div className="pitch-connect-grid pitch-connect-ai-grid">
      <div className="pitch-panel pitch-panel-dark pitch-ai-demo">
        <div className="pitch-section-heading"><span className="pitch-chip is-available">● {live ? 'Interactive designer' : 'Actual app screenshot'}</span><div className="pitch-segment" aria-label="AI designer view"><button type="button" aria-pressed={view === '2d'} onClick={() => setView('2d')}>2D plan</button><button type="button" aria-pressed={view === '3d'} onClick={() => setView('3d')}>Premium 3D</button></div></div>
        {live ? <EmbeddedDesigner scene="home" view={view} onViewChange={setView} panel="ai" pitch className="pitch-designer-frame" title="Interactive AI house design workspace" /> : <button className="pitch-ai-capture" type="button" onClick={() => setLive(true)} aria-label="Open interactive AI designer"><img src={view === '2d' ? '/showcase/designer-plan.webp' : '/showcase/designer-ai.png'} alt={`Actual Room Designer ${view === '2d' ? '2D plan' : 'AI design assistant with a measured draft'} workspace; open the live demo to use the tools`} /><span>Open the working designer <span aria-hidden="true">↗</span></span></button>}
        <p className="pitch-fine">Guided drafts work locally. AI drafting needs sign-in and a configured provider. Demo edits never place orders.</p>
      </div>
      <aside className="pitch-panel pitch-panel-ivory"><p className="pitch-eyebrow">Brief → draft → review</p><h3>{story.heading}</h3><p>Start with measured guided inputs, or describe a brief to AI. Review the proposed rooms before applying.</p><blockquote className="pitch-ai-prompt">“{story.prompt}”</blockquote><ol className="pitch-ai-steps"><li><strong>Describe.</strong> Set dimensions or write a brief.</li><li><strong>Review.</strong> Check rooms and measurements.</li><li><strong>Refine.</strong> Apply, edit and undo.</li></ol><details className="pitch-ai-review-note"><summary>What to review</summary><p>{story.outcome} Planning drafts need professional site, regulatory and engineering review.</p></details><div className="pitch-enquiry-actions"><button type="button" className="pitch-primary" onClick={() => setLive(true)}>Try the AI workspace ↗</button><a className="pitch-secondary" href="/demo?view=3d&panel=ai&pitch=1" target="_blank" rel="noreferrer">Open full screen ↗</a></div></aside>
    </div>}
    {section === 'connect' && <div className="pitch-connect-grid"><aside className="pitch-panel pitch-panel-ivory"><p className="pitch-eyebrow">Start with your data</p><h3>Your catalogue.<br />Your workflow.</h3><p>{story.connection}</p><ol className="pitch-ai-steps"><li><strong>Prepare:</strong> product identifiers, dimensions, prices, units and images.</li><li><strong>Validate:</strong> review mappings, sample products and data quality.</li><li><strong>Connect:</strong> assign access and agree publishing and order permissions.</li></ol><a className="pitch-primary" href="/studio/merchants/connect">Prepare a merchant connection ↗</a><p className="pitch-fine">Setup is reviewable before publishing. Do not paste passwords or production API keys into a demo or an enquiry.</p></aside><article className="pitch-panel pitch-panel-dark"><p className="pitch-eyebrow">Tools that connect</p><h3>Tools that work together.</h3><div className="pitch-automation-cards"><div><span>DESIGN</span><strong>Guided drafts + AI workspace</strong><p>Use measured inputs now, or connect a configured AI provider. Inspect the proposal before applying it.</p></div><div><span>MEASURE</span><strong>Materials + energy</strong><p>Recalculate quantities from the plan with visible assumptions. Review solar and electrical estimates.</p></div><div><span>CONNECT</span><strong>MCP tool access</strong><p>Compatible AI clients can inspect the schema, search products, estimate materials and foundations, and generate or validate a draft. Review dimensions and assumptions before applying a design; these tools cannot place orders.</p></div><div><span>AUTHORIZE</span><strong>Procurement workflow</strong><p>Approval deadlines, contractor bookings and automatic ordering require agreed supplier integrations. This pitch does not activate them.</p></div></div><button type="button" className="pitch-secondary" onClick={() => setSection('contact')}>Discuss your workflow ↗</button></article></div>}
    {section === 'contact' && <div className="pitch-connect-grid pitch-contact-grid"><aside className="pitch-panel pitch-panel-dark"><p className="pitch-eyebrow">Build the next step together</p><h3>A useful conversation.<br />A practical next step.</h3><p>Share a project, tell us what needs improving, or request a visit to your office or site.</p><a className="pitch-primary" href={MEETING_URL} target="_blank" rel="noreferrer">Book a 1-hour video meeting ↗</a><div className="pitch-contact-person"><span className="pitch-avatar">VC</span><div><strong>Victor Cassius Bhatoolaul</strong><p>Your partner for workflow ideas, implementation and ongoing improvements.</p></div></div><p className="pitch-fine">In-person meetings are requested through the form. We will agree the location and time before anything is confirmed.</p></aside><div className="pitch-panel pitch-panel-ivory"><PitchEnquiryForm audience={audience} /></div></div>}
  </div>;
}
